---
- hosts: load_balancer
  become: true
  become_user: root
  tasks:

  - name: Install nginx
    apt:
      name:
       - nginx
      state: latest
      update_cache: yes

  - name: Install keepalived
    apt:
      name:
       - keepalived
      state: latest
      update_cache: yes

  - name: Install libipset13
    apt:
      name:
       - libipset13
      state: latest
      update_cache: yes

  - name: Copy load-balancer.conf
     template:
       src: load-balancer.conf
       dest: /etc/nginx/sites-enabled/load-balancer.conf
       mode: 0644
       owner: root
       group: root

