---
- hosts: all_servers
  become: true
  become_user: root

  tasks:
   - name: Copy sample.html
     template:
       src: sample.html
       dest: /var/www/html/sample.html
       mode: 0644
       owner: root
       group: root
