---
- hosts: backup_load_balancer
  become: true
  become_user: root

  tasks:
   - name: Copy keepalived.conf
     template:
       src: lb2/keepalived.conf
       dest: /etc/keepalived/keepalived.conf
       mode: 0644
       owner: root
       group: root
