---

- hosts: load_balancer
  become: true
  tasks:

    #- name: Enable keepalived
      #service:
       #name: keepalived
       #state: enabled

    - name: restart keepalived
      service:
       name: keepalived
       state: restarted

